import nodemailer from 'nodemailer';
import User from '@/models/User';
import bcryptjs from 'bcryptjs';

export const sendEmail = async({email, emailType, userId}) =>{
    try{
        //create a hashed token
        const hashedToken = await bcryptjs.hash(userId.toString(), 10);

        if(emailType === "VERIFY"){
            await User.findByIdAndUpdate(userId,
            {
                verifyToken: hashedToken,
                verifyTokenExpiry: Date.now() + 3600000
            })
        } else if(emailType === "RESET"){
            await User.findByIdAndUpdate(userId,
            {
                forgotPasswordToken: hashedToken,
                forgotPasswordExpiry: Date.now() + 3600000
            })
        } 
        var transport = nodemailer.createTransport({
            //it is better to use variables name and put the  in .env 
            //These values:are generated by Mailtrap and must 
            // stay exactly as provided, otherwise authentication
            //  will fail.
            //
            host: process.env.MAILTRAP_HOST,
            port: Number(process.env.MAILTRAP_PORT),
            auth: {
                user: process.env.MAILTRAP_USER,
                pass: process.env.MAILTRAP_PASS
            }
        });
        const mailOptions = {
            from: "emwardeh1995@hotmail.com",
            to: email,
            subject:
                emailType === "VERIFY"
                ? "Verify your email"
                : "Reset your password",

            html: `
                <div style="font-family: Arial, sans-serif; padding: 20px;">
                    <h2>
                        ${
                        emailType === "VERIFY"
                            ? "Verify Your Email"
                            : "Reset Your Password"
                        }
                    </h2>

                    <p>
                        ${
                        emailType === "VERIFY"
                            ? "Thank you for signing up. Please verify your email by clicking the button below."
                            : "Click the button below to reset your password."
                        }
                    </p>

                    <a 
                        href="${process.env.DOMAIN}/${
                        emailType === "VERIFY" ? "verifyemail" : "resetpassword"
                        }?token=${hashedToken}"
                        style="
                        display: inline-block;
                        padding: 10px 20px;
                        background-color: #007bff;
                        color: white;
                        text-decoration: none;
                        border-radius: 5px;
                        "
                    >
                        ${
                        emailType === "VERIFY"
                            ? "Verify Email"
                            : "Reset Password"
                        }
                    </a>

                    <p style="margin-top: 20px;">
                        If you did not request this, you can ignore this email.
                    </p>
                </div>
            `,
        };
        const mailRespone = await transport.sendMail(mailOptions);
        return mailRespone;
    } catch(error){
        throw new Error(error.message);
    }
}